# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1NwHm9eEaKKpoSWihTGN_pZg9L4-ILV9T
"""

# Install pgmpy if not already installed
# pip install pgmpy

from pgmpy.models import DiscreteBayesianNetwork
from pgmpy.estimators import MaximumLikelihoodEstimator
from pgmpy.inference import VariableElimination
import pandas as pd

# -----------------------------
# Step 1: Create sample dataset
# -----------------------------
data = pd.DataFrame({
    'Rain': ['No', 'No', 'Yes', 'Yes', 'No', 'Yes', 'Yes', 'No'],
    'TrafficJam': ['Yes', 'No', 'Yes', 'No', 'Yes', 'Yes', 'No', 'No'],
    'ArriveLate': ['Yes', 'No', 'Yes', 'No', 'No', 'Yes', 'Yes', 'No']
})

print("Dataset:\n", data, "\n")

# ---------------------------------------
# Step 2: Define Bayesian Network structure
# ---------------------------------------
model = DiscreteBayesianNetwork([
    ('Rain', 'TrafficJam'),
    ('TrafficJam', 'ArriveLate')
])

# ---------------------------------------
# Step 3: Fit model using MLE
# ---------------------------------------
model.fit(data, estimator=MaximumLikelihoodEstimator)

# ---------------------------------------
# Step 4: Print CPDs (Conditional Probabilities)
# ---------------------------------------
print("Conditional Probability Distributions (CPDs):\n")
for cpd in model.get_cpds():
    print(cpd)
    print()

# ---------------------------------------
# Step 5: Perform inference
# ---------------------------------------
inference = VariableElimination(model)

# Query: P(ArriveLate | Rain = Yes)
query_result = inference.query(
    variables=['ArriveLate'],
    evidence={'Rain': 'Yes'}
)

# ---------------------------------------
# Step 6: Display result
# ---------------------------------------
print("Inference Result: P(ArriveLate | Rain = Yes)\n")
print(query_result)

# ---------------------------------------
# Optional: Query more cases
# ---------------------------------------
print("\nAdditional Queries:\n")

# P(ArriveLate | Rain = No)
result2 = inference.query(
    variables=['ArriveLate'],
    evidence={'Rain': 'No'}
)
print("P(ArriveLate | Rain = No):")
print(result2)

# P(TrafficJam | Rain = Yes)
result3 = inference.query(
    variables=['TrafficJam'],
    evidence={'Rain': 'Yes'}
)
print("\nP(TrafficJam | Rain = Yes):")
print(result3)

!pip install pgmpy

# Install pgmpy if not already installed
# pip install pgmpy

from pgmpy.models import DiscreteBayesianNetwork
from pgmpy.estimators import MaximumLikelihoodEstimator
from pgmpy.inference import VariableElimination
import pandas as pd

# -----------------------------
# Step 1: Create sample dataset
# -----------------------------
data = pd.DataFrame({
    'Rain': ['No', 'No', 'Yes', 'Yes', 'No', 'Yes', 'Yes', 'No'],
    'TrafficJam': ['Yes', 'No', 'Yes', 'No', 'Yes', 'Yes', 'No', 'No'],
    'ArriveLate': ['Yes', 'No', 'Yes', 'No', 'No', 'Yes', 'Yes', 'No']
})

print("Dataset:\n", data, "\n")

# ---------------------------------------
# Step 2: Define Bayesian Network structure
# ---------------------------------------
model = DiscreteBayesianNetwork([
    ('Rain', 'TrafficJam'),
    ('TrafficJam', 'ArriveLate')
])

# ---------------------------------------
# Step 3: Fit model using MLE
# ---------------------------------------
model.fit(data, estimator=MaximumLikelihoodEstimator)

# ---------------------------------------
# Step 4: Print CPDs (Conditional Probabilities)
# ---------------------------------------
print("Conditional Probability Distributions (CPDs):\n")
for cpd in model.get_cpds():
    print(cpd)
    print()

# ---------------------------------------
# Step 5: Perform inference
# ---------------------------------------
inference = VariableElimination(model)

# Query: P(ArriveLate | Rain = Yes)
query_result = inference.query(
    variables=['ArriveLate'],
    evidence={'Rain': 'Yes'}
)

# ---------------------------------------
# Step 6: Display result
# ---------------------------------------
print("Inference Result: P(ArriveLate | Rain = Yes)\n")
print(query_result)

# ---------------------------------------
# Optional: Query more cases
# ---------------------------------------
print("\nAdditional Queries:\n")

# P(ArriveLate | Rain = No)
result2 = inference.query(
    variables=['ArriveLate'],
    evidence={'Rain': 'No'}
)
print("P(ArriveLate | Rain = No):")
print(result2)

# P(TrafficJam | Rain = Yes)
result3 = inference.query(
    variables=['TrafficJam'],
    evidence={'Rain': 'Yes'}
)
print("\nP(TrafficJam | Rain = Yes):")
print(result3)